Testing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -60,84 +60,84 @@ jobs:
       matrix:
         goversion:
           - 1.20.x
-  publish_sdk:
-    name: Publish SDKs
-    runs-on: ubuntu-latest
-    needs: publish_binary
-    permissions:
-      id-token: write
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v4
-        with:
-          fetch-tags: true
-          fetch-depth: 0
-      - name: Install Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: ${{ matrix.goversion }}
-          cache-dependency-path: |
-            provider/go.sum
-            sdk/go.sum
-      - name: Install pulumictl
-        uses: jaxxstorm/action-install-gh-release@v1.10.0
-        with:
-          repo: pulumi/pulumictl
-      - name: Install Pulumi CLI
-        uses: pulumi/action-install-pulumi-cli@v2.0.0
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{matrix.nodeversion}}
-          registry-url: ${{env.NPM_REGISTRY_URL}}
-      - name: Setup DotNet
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: ${{matrix.dotnetversion}}
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{matrix.pythonversion}}
-      - name: Build SDK
-        run: make build_${{ matrix.language }}
-      - name: Check worktree clean
-        run: |
-          git update-index -q --refresh
-          if ! git diff-files --quiet; then
-              >&2 echo "error: working tree is not clean, aborting!"
-              git status
-              git diff
-              exit 1
-          fi
-      - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
-        name: Publish package to PyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          packages_dir: ${{github.workspace}}/sdk/python/bin/dist
-      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
-        uses: JS-DevTools/npm-publish@v3
-        with:
-          access: "public"
-          token: ${{ env.NPM_TOKEN }}
-          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
-      - if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
-        name: publish nuget package
-        run: |
-          dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
-          echo "done publishing packages"
-    strategy:
-      fail-fast: true
-      matrix:
-        dotnetversion:
-          - 3.1.301
-        goversion:
-          - 1.20.x
-        language:
-          - nodejs
-          - python
-          - dotnet
-          - go
-        nodeversion:
-          - 14.x
-        pythonversion:
-          - "3.9"
+  # publish_sdk:
+  #   name: Publish SDKs
+  #   runs-on: ubuntu-latest
+  #   needs: publish_binary
+  #   permissions:
+  #     id-token: write
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-tags: true
+  #         fetch-depth: 0
+  #     - name: Install Go
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         go-version: ${{ matrix.goversion }}
+  #         cache-dependency-path: |
+  #           provider/go.sum
+  #           sdk/go.sum
+  #     - name: Install pulumictl
+  #       uses: jaxxstorm/action-install-gh-release@v1.10.0
+  #       with:
+  #         repo: pulumi/pulumictl
+  #     - name: Install Pulumi CLI
+  #       uses: pulumi/action-install-pulumi-cli@v2.0.0
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: ${{matrix.nodeversion}}
+  #         registry-url: ${{env.NPM_REGISTRY_URL}}
+  #     - name: Setup DotNet
+  #       uses: actions/setup-dotnet@v3
+  #       with:
+  #         dotnet-version: ${{matrix.dotnetversion}}
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{matrix.pythonversion}}
+  #     - name: Build SDK
+  #       run: make build_${{ matrix.language }}
+  #     - name: Check worktree clean
+  #       run: |
+  #         git update-index -q --refresh
+  #         if ! git diff-files --quiet; then
+  #             >&2 echo "error: working tree is not clean, aborting!"
+  #             git status
+  #             git diff
+  #             exit 1
+  #         fi
+  #     - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
+  #       name: Publish package to PyPI
+  #       uses: pypa/gh-action-pypi-publish@release/v1
+  #       with:
+  #         packages_dir: ${{github.workspace}}/sdk/python/bin/dist
+  #     - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
+  #       uses: JS-DevTools/npm-publish@v3
+  #       with:
+  #         access: "public"
+  #         token: ${{ env.NPM_TOKEN }}
+  #         package: ${{github.workspace}}/sdk/nodejs/bin/package.json
+  #     - if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
+  #       name: publish nuget package
+  #       run: |
+  #         dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
+  #         echo "done publishing packages"
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       dotnetversion:
+  #         - 3.1.301
+  #       goversion:
+  #         - 1.20.x
+  #       language:
+  #         - nodejs
+  #         - python
+  #         - dotnet
+  #         - go
+  #       nodeversion:
+  #         - 14.x
+  #       pythonversion:
+  #         - "3.9"
